WordHeaven-Web/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WordHeaven_Web.Data;
using WordHeaven_Web.Data.Entity;

namespace WordHeaven_Web.Controllers
{
    public class LivrosController : Controller
    {
        private readonly DataContext _context;

        public LivrosController(DataContext context)
        {
            _context = context;
        }

        // GET: Livros
        public async Task<IActionResult> Index()
        {
            return View(await _context.Livros.ToListAsync());
        }

        // GET: Livros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Editora,AnoDePublicacao,Resumo,Idioma,NumeroPaginas,Tematica,Desconto,Valor")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Livros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,Editora,AnoDePublicacao,Resumo,Idioma,NumeroPaginas,Tematica,Desconto,Valor")] Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livro = await _context.Livros.FindAsync(id);
            _context.Livros.Remove(livro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
            return _context.Livros.Any(e => e.Id == id);
        }
    }
}

WordHeaven-Web/Views/Shared/_Layout.cshtml
@using WordHeaven_Web.Data.Entity;
@using Microsoft.AspNetCore.Identity;
@using WordHeaven_Web.Controllers
@using WordHeaven_Web.Helpers
@inject UserManager<User> UserManager
@inject SignInManager<User> SignInManager
@inject RoleManager<IdentityRole> RoleManager

<!DOCTYPE html>
<html lang="en">

@{
    ViewData["Title"] = "WordHeaven";
    var user = await UserManager.GetUserAsync(User);
    @if (user != null)
    {
        var role = await UserManager.GetRolesAsync(user);
        ViewData["FullName"] = user.FullName;
        ViewData["Role"] = role[0];

        var base64 = Convert.ToBase64String(user.PictureSource);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        ViewData["Image"] = imgSrc;
    }

}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-cyborg-gaming.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">               
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a asp-area="" asp-controller="Home" asp-action="Home" class="logo">
                            <img src="~/assets/images/logo.png" alt=""/>
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Search End ***** -->
                        <div class="search-input">
                            <form id="search" action="#">
                                <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                                <i class="fa fa-search"></i>
                            </form>
                        </div>
                        <!-- ***** Search End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Home" class="active" style="color:white;">Home</a></li>
                            <li><a asp-area="" asp-controller="Livros" asp-action="Index" style="color:white;">Books</a></li>
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <li><a asp-area="" asp-controller="Account" asp-action="Logout" style="color:white;"><i class="fa fa-sign-in fa-solid"></i> Logout</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="AccountManagement" style="color:white;">@ViewData["FullName"]<img src="@ViewData["Image"]" alt=""></a></li>
                               
                            }
                            else
                            {
                                <li><a asp-area="" asp-controller="Account" asp-action="Login" style="background-color:#e75e8d; color:white;"><i class="fa fa-sign-out fa-solid"></i> Login</a></li>
                            }
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">

                    <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/assets/js/isotope.min.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/tabs.js"></script>
    <script src="~/assets/js/popup.js"></script>
    <script src="~/assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>